version: '3'

services:
  express-server:
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
  redis:
    image: redis
    ports:
      - "6379:6379"